A few type fixes
moleculerjs/moleculer pull request #834
Opened 2020-10-25 21:18 UTC by Brian-McBride

## :memo: Description
While building a new discoverer module, I ran across a few typing issues. 

-----
## ISSUE: Register function expects args depending on metrics type
```javascript
this.broker.metrics.register({
      name: MOLECULER_DISCOVERER_REDIS_COLLECT_TOTAL,
      type: METRIC.TYPE_COUNTER,
      rate: true, // TODO This value is not typed in BaseMetricOptions (as well as others)
      description: "Number of Service Registry fetching from Redis",
    })
```
Adding additional key/values to BaseMetricOptions to support existing metics libs (quick fix)

Ideally, there should be a base interface, then interfaces made for each Metric Type, then union them with the `type` key identifying which union it is. Or, have a declarative pattern. 

## Missing function type
Adding resolve function to the Serializers object. 

## Missing return types
Adding `BrokerNode` as a return type for the methods `disoverNode` and `discoveryAllNodes`

### :dart: Relevant issues

### :gem: Type of change

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## :checkered_flag: Checklist:

- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my own code
- [ ] **I have added tests that prove my fix is effective or that my feature works**
- [ ] **New and existing unit tests pass locally with my changes**
- [ ] I have commented my code, particularly in hard-to-understand areas

2020-10-26 10:33 UTC, icebob requested changes

2020-10-26 10:33 UTC, icebob commented on index.d.ts
> +		before?: (ctx: Context<any, any>) => Promise<void> | void;
Why did you remove the `string` types?

2020-10-26 18:12 UTC, Brian-McBride reviewed
I backed out those differences. Honestly, no idea where they came from, I wasn't paying attention.

2020-10-27 17:37 UTC, icebob approved these changes
Thanks

2020-10-27 17:37 UTC, merged